name: Deploy to Mini PC

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to Mini PC
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: jakes-linux.tailnet-xxxx.ts.net
          username: botuser
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd ~/crypto-bot
            git pull
            sudo systemctl restart cryptobot
